name: dog food - tests

on: [push, pull_request, pull_request_target, workflow_dispatch]

# Allow one concurrent deployment
concurrency:
  group: ${{ github.event_name }}-${{ github.base_ref }}-${{ github.head_ref || github.event.number }}
  cancel-in-progress: true

jobs:
  ghdiag:
    name: Run GitHub diagnostic
    if: ${{ vars.ACTIONS_RUNNER_DEBUG || vars.ACTIONS_STEP_DEBUG }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        uses: actions/github-script@v6
        with:
          script: |
            core.debug('!!! START github START !!!')
            core.info(JSON.stringify(github, null, '  '))
            core.debug('!!! END github END !!!')

            core.debug('!!! START context START !!!')
            core.info(JSON.stringify(context, null, '  '))
            core.debug('!!! END context END !!!')
      - run: printenv

  gitleaks:
    runs-on: ubuntu-latest
    name: Run Gitleaks
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        id: gitleaks
        uses: ./
        with:
          report_format: sarif
          fail: false

      - name: Get the output from the gitleaks step
        run: |
          echo "exitcode: ${{ steps.gitleaks.outputs.exitcode }}"
          echo "result: ${{ steps.gitleaks.outputs.result }}"
          echo "output: ${{ steps.gitleaks.outputs.output }}"
          echo "command: ${{ steps.gitleaks.outputs.command }}"
          echo "report: ${{ steps.gitleaks.outputs.report }}"

      - name: Upload SARIF report
        if: ${{ steps.gitleaks.outputs.exitcode == 1 }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.gitleaks.outputs.report }}
